### ISSUE TITLE
what's the problem when i run on hmdb51 datasets

### ISSUE THREAD

**Issue by zys20172212265** [feiyunzhang/i3d-nonlocal-pytorch#3]
File "/home/z/i3d-non-local-pytorch/dataset.py", line 78, in _sample_indices
    offsets = np.sort(randint(record.num_frames, size=self.sample_frames))
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by feiyunzhang** [comment]
it needs record.num_frames < self.sample_frames ,because it needs sample_frames(32  ) frames to input the network.

**Comment by zys20172212265** [comment]
@feiyunzhang  thanks for your reply!
https://github.com/feiyunzhang/i3d-non-local-pytorch/blob/33596cdc6b003ed1301175af5842e8bb694cbfcf/dataset.py#L61

yes ,i know the code here is to  sample 32 frames, i set sample_frames=32,but when i train nearly 1 epoch,it meet the follow question,i dont know why

Epoch: [0][320/447], lr: 0.00100        Time 2.109 (1.070)      Data 1.148 (0.058)      Loss 3.9130 (14.0998)   Prec@1 12.500 (2.064)   Prec@5 37.500 (8.801)
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 157, in train
    for i, (input, target) in enumerate(train_loader):
  File "/home/z/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/home/z/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/z/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/z/anaconda3/envs/py3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/z/tsn-pytorch/dataset.py", line 128, in __getitem__
    segment_indices = self._sample_indices(record) if self.random_shift else self._get_val_indices(record)
  File "/home/z/tsn-pytorch/dataset.py", line 86, in _sample_indices
    offsets = np.sort(randint(record.num_frames, size=self.sample_frames))
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by feiyunzhang** [comment]
Maybe your record.num_frames = 0, it will get this error, please check

**Comment by zys20172212265** [comment]
@feiyunzhang  oh,yes.thanks,i find .but when i run on hmdb dataset, loss decrease very slow by change other 3d model ,any idea?

**Comment by feiyunzhang** [comment]
if you run nonlocal, you can fist run i3d/c3d then nonlocal, follow the paper
